definitions:
  dto.BurnFileDTO:
    properties:
      callbackStatus:
        type: integer
      callbackUrl:
        example: http://localhost:8010/api/v1/callback
        type: string
      done_status:
        type: integer
      fileUrl:
        example: https://static.runoob.com/images/demo/demo1.jpg
        type: string
      odaSavePath:
        example: D:/downloadVideo
        type: string
      taskId:
        example: 1
        type: integer
    type: object
  dto.BurnMix3VideoDTO:
    properties:
      callBackUrl:
        example: http://localhost:8010/api/v1/callback
        type: string
      endTime:
        example: "2022-05-11 15:25:00"
        type: string
      fileSavePath:
        type: string
      odaSavePath:
        example: D:/downloadVideo
        type: string
      rtspUrlLeft:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=1
        type: string
      rtspUrlMiddle:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=0
        type: string
      rtspUrlRight:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=1
        type: string
      startTime:
        example: "2022-05-11 15:20:00"
        type: string
      taskId:
        example: 1
        type: integer
      temperature:
        example: ""
        type: string
      videoName:
        type: string
    required:
    - endTime
    - rtspUrlLeft
    - rtspUrlMiddle
    - rtspUrlRight
    - startTime
    type: object
  dto.BurnSettingDTO:
    properties:
      encryptionType:
        type: integer
      odaSavePath:
        example: D:/videodata
        type: string
      password:
        type: string
      taskNum:
        example: 1
        type: integer
      videoName:
        example: video
        type: string
    required:
    - odaSavePath
    - taskNum
    type: object
  dto.BurnSingleVideoDTO:
    properties:
      callBackUrl:
        example: http://localhost:8010/api/v1/callback
        type: string
      endTime:
        example: "2022-05-11 15:25:00"
        type: string
      fileSavePath:
        type: string
      odaSavePath:
        example: D:/downloadVideo
        type: string
      rtspUrl:
        example: rtsp://admin:cebon61332433@192.168.99.215:554/cam/realmonitor?channel=1&subtype=0
        type: string
      startTime:
        example: "2022-05-11 15:20:00"
        type: string
      taskId:
        example: 1
        type: integer
      videoName:
        type: string
    required:
    - endTime
    - rtspUrl
    - startTime
    type: object
  response.Response:
    properties:
      code:
        description: 响应码
        type: integer
      data:
        description: 响应数据
      msg:
        description: 响应消息
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/burnFile:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: fileReq
        required: true
        schema:
          $ref: '#/definitions/dto.BurnFileDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 文件
      tags:
      - 下载
  /api/v1/burnMixVideo:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: mix3Req
        required: true
        schema:
          $ref: '#/definitions/dto.BurnMix3VideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 三合一
      tags:
      - 下载
  /api/v1/burnOtherSingleParams:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: publicReq
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 公区
      tags:
      - 下载参数
  /api/v1/burnOtherSingleVideo:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: publicReq
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 公区
      tags:
      - 下载
  /api/v1/burnParams:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: burnMix3VideoDTO
        required: true
        schema:
          $ref: '#/definitions/dto.BurnMix3VideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 三合一
      tags:
      - 下载参数
  /api/v1/burnSingleParams:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: singleReq
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 房间单画面
      tags:
      - 下载参数
  /api/v1/burnSingleVideo:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: singleReq
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 房间
      tags:
      - 下载
  /api/v1/burnTask:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: burnSettingDTO
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSettingDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 创建刻录任务
      tags:
      - 刻录任务
  /api/v1/monitor/web/mix:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.BurnMix3VideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 三合一
      tags:
      - 回放
  /api/v1/monitor/web/other:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 公区
      tags:
      - 回放
  /api/v1/monitor/web/single:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.BurnSingleVideoDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: 房间单画面
      tags:
      - 回放
swagger: "2.0"
