server:
  profile: dev
  name: burn
  ip: 127.0.0.1
  port: 8004

log:
  dir: logs
  maxSize: 200
  maxAge: 90
  maxBackups: 100
  compress: true
  localtime: true
  showLine: true

mysql:
  conn_max_lifetime: 1h
  max_idle_conns: 1
  max_open_conns: 10

swagger:
#  http://localhost:8080/doc/index.html
  title: 视频刻录服务文档
  desc:
  host: ""
  url: /doc
  basePath: /
  schemes:
    - http

ffmpeg:
  libPath: lib/ffmpeg/ffmpeg.exe

